# -----------------------------------------
# THIS FILE WAS AUTOGENERATED! DO NOT EDIT!
# -----------------------------------------
# file to edit: 02_foobar.ipynb

def foo(x):
    return x + 1

def bar(x):
    return foo(x)*2
