# -----------------------------------------
# THIS FILE WAS AUTOGENERATED! DO NOT EDIT!
# -----------------------------------------
# file to edit: 00a_annotations.ipynb

from torch.nn import Module
from typing import Callable, List, Optional

Activation = Callable
MaybeActivation = Optional[Activation]
ListOfModules = List[Module]
