# -----------------------------------------
# THIS FILE WAS AUTOGENERATED! DO NOT EDIT!
# -----------------------------------------
# file to edit: 00a_annotations.ipynb

from torch.nn import Module
from typing import Callable, List, Optional, Union, Tuple, Any, Dict


Activation = Callable
Loss = Callable
MaybeActivation = Optional[Activation]
Func = Union[Callable, str]
Size = Tuple[int, int]
