# -----------------------------------------
# THIS FILE WAS AUTOGENERATED! DO NOT EDIT!
# -----------------------------------------
# file to edit: 00b_config.ipynb

from pathlib import Path
from multiprocessing import cpu_count

import torch
from torch.nn import functional as F


class Config:

    @property
    def batch_size(self): return 4

    @property
    def bs(self): return self.batch_size

    @property
    def cpu(self): return torch.device('cpu')

    @property
    def gpu_index(self): return 0

    @property
    def gpu(self): return torch.device(f'cuda:{self.gpu_index}')

    @property
    def device(self): return self.gpu

    @property
    def datasets(self): return Path.home()/'data'

    @property
    def loss_function(self): return F.nll_loss

    @property
    def loss_fn(self): return self.loss_function

    @property
    def num_workers(self): return cpu_count()

    @property
    def n_jobs(self): return self.num_workers


defaults = Config()
