# -----------------------------------------
# THIS FILE WAS AUTOGENERATED! DO NOT EDIT!
# -----------------------------------------
# file to edit: 00_config.ipynb

from pathlib import Path

import torch


class Config:
    @property
    def batch_size(self): return 4

    @property
    def bs(self): return self.batch_size

    @property
    def cpu(self): return torch.device('cpu')

    @property
    def gpu_index(self): return 0

    @property
    def gpu(self): return torch.device(f'cuda:{self.gpu_index}')

    @property
    def device(self): return self.gpu()

    @property
    def datasets(self): return Path.home()/'data'


defaults = Config()
