# -----------------------------------------
# THIS FILE WAS AUTOGENERATED! DO NOT EDIT!
# -----------------------------------------
# file to edit: 03d_visdom.ipynb

import os
from collections import ChainMap

from visdom import Visdom

from loop.callbacks import Callback, Order


class VisdomDashboard(Callback):

    order = Order.Logging()

    def __init__(self, show_opt_params: bool=False, batch_freq: int=1, **visdom_conf):
        self.show_opt_params = show_opt_params
        self.batch_freq = batch_freq
        self.visdom_conf = visdom_conf
        self.vis = None

    def training_started(self, **kwargs):
        username = self.visdom_conf.get('username', os.environ.get('VISDOM_USERNAME'))
        password = self.visdom_conf.get('password', os.environ.get('VISDOM_PASSWORD'))
        server = self.visdom_conf.get('server', '0.0.0.0')
        port = int(self.visdom_conf.get('port', 9090))
        self.vis = Visdom(server=server, port=port, username=username, password=password)

    def batch_ended(self, phase, **kwargs):
        x = phase.batch_index

        if phase.grad:
            if self.show_opt_params:
                opt = self.group.opt
                for i, params in enumerate(opt.param_groups):
                    title = f'LR [group: {i}]'
                    self.vis.line(
                        X=[x], Y=[params['lr']], win=title, name='lr',
                        opts=dict(title=title), update='append')

        if x % self.batch_freq == 0:
            self.vis.line(
                X=[x], Y=[phase.batch_loss], win=phase.name, name='batch_loss',
                opts=dict(title=f'Running Batch Loss [{phase.name}]'), update='append')

    def epoch_ended(self, phases, epoch, **kwargs):
        metrics = dict(ChainMap(*[phase.last_metrics for phase in phases]))
        for name, value in metrics.items():
            phase, metric_name = name.split('_')
            self.vis.line(
                X=[epoch], Y=[value], win=metric_name, name=phase,
                opts=dict(title=metric_name), update='append')
